### ISSUE TITLE
Can write when operator and account are missing

### ISSUE THREAD

**Issue by ruspaul013** [edgefarm/vault-plugin-secrets-nats#23]
Hello!

while I was trying different things with this plugin, I observed that I can write to a user path where I do not have any operator, account. 

```
[root@base-machine example]# vault write nats-secrets/issue/operator/local/account/myaccount/user/user @account/myuser.json
Success! Data written to: nats-secrets/issue/operator/local/account/myaccount/user/user
[root@base-machine example]# vault read nats-secrets/issue/operator/local
Error reading nats-secrets/issue/operator/local: Error making API request.

URL: GET http://127.0.0.1:8200/v1/nats-secrets/issue/operator/local
Code: 400. Errors:

* issue not found

```
Is this the behavior you want?

**Comment by siredmar** [comment]
Hi @ruspaul013 
Thanks for raising this issue. During writing this i found a bug that prevented proper jwt creation if in the wrong order.
Nevertheless, the mentioned issue is only slightly affected. For your tests please use >= v1.5.1 (just released).

I'll try to explain what happens here:
You were writing the `issue` for user `user` in account `myaccount` in operator `local`. 
So, if you read back the same issue, it should be existent.

```
$ vault write nats-secrets/issue/operator/local/account/myaccount/user/user @account/myuser.json
Success! Data written to: nats-secrets/issue/operator/local/account/myaccount/user/user

$ vault read nats-secrets/issue/operator/local/account/myaccount/user/user
vault read nats-secrets/issue/operator/local/account/myaccount/user/user
Key              Value
---              -----
account          myaccount
claims           map[user:map[data:-1 payload:-1 pub:map[] sub:map[] subs:-1]]
operator         local
status           map[user:map[jwt:false nkey:true]]
useSigningKey    n/a
user             user
```

The NKey identifying the user are created. However, the JWT that is used to decode the capabilities of the user cannot be created, because the signer (the account) does not exist yet.

```
$ vault read nats-secrets/nkey/operator/local/account/myaccount/user/user
Key           Value
---           -----
privateKey    PCHPDDSPCBDGI47L3SRW3V4G6T5HASCNHD5BH545WTGTR6AJWC7XWAXXIN2NURJLLC6ZHCKHIWYG7UZ4WSVBSCSXLIPYWIOIHTEEXOOGSMCQ
publicKey     UABPOQ3U3JCSWWF5SOEUORNQN7JTZNFKDEFFOWQ7RMQ4QPGIJO44N5QX
seed          SUAI54MOJ4IEMZDT5POKG3OXQ32PU4CIJU4PUE7XTW2M2OHYBGYL6642DM

$ vault read nats-secrets/jwt/operator/local/account/myaccount/user/user
Error reading nats-secrets/jwt/operator/local/account/myaccount/user/user: Error making API request.

URL: GET http://127.0.0.1:8200/v1/nats-secrets/jwt/operator/local/account/myaccount/user/user
Code: 400. Errors:

* jwt not found
```

Now, lets create the account by creating the account issue. We will see that the JWT for the account is also not created. This is, because the signing instance (the operator) does not exist yet. 

```
$ vault write nats-secrets/issue/operator/local/account/myaccount @account/myaccount.json 
Error writing data to nats-secrets/issue/operator/local/account/myaccount: Error making API request.

URL: PUT http://127.0.0.1:8200/v1/nats-secrets/issue/operator/local/account/myaccount
Code: 400. Errors:

* adding issue failed: operator nkey does not exist: local - Cannot create JWT

$ vault read nats-secrets/issue/operator/local/account/myaccount                         
Key              Value
---              -----
account          myaccount
claims           map[account:map[defaultPermissions:map[pub:map[] sub:map[]] limits:map[conn:-1 data:-1 exports:-1 imports:-1 leafNodeConn:-1 payload:-1 subs:-1 wildcardExports:true]]]
operator         local
status           map[account:map[jwt:false nkey:false] accountServer:map[lastSync:0 synced:false]]
useSigningKey    n/a

$ vault read nats-secrets/nkey/operator/local/account/myaccount    
Key           Value
---           -----
privateKey    PC24SCXYWIEEUSJA5SU3P2E3NDJ5S22OA7XUBA2JTNFQCSHA3YOKFFN6GQ2X3PWROOMS7QIGFKFUEFYOBSR7BATAG5VTMDKRCESLQMMBIN4A
publicKey     ACK34NBVPW7NC44ZF7AQMKULIILQ4DFD6CBGAN3LGYGVCEJEXAYYC2XK
seed          SAALLSIK7CZAQSSJEDWKTN7ITNUNHWLLJYD66QEDJGNUWAKI4DPBZIWFDU

$ vault read nats-secrets/jwt/operator/local/account/myaccount                         
Error reading nats-secrets/jwt/operator/local/account/myaccount: Error making API request.

URL: GET http://127.0.0.1:8200/v1/nats-secrets/jwt/operator/local/account/myaccount
Code: 400. Errors:

* jwt not found
```

After creating the the account that adds the NKey for signing the user, the `user` JWT will be created. This at least completes the chain of trust for the user. The user is trusted, if it is signed by an account. 

```
$ vault read nats-secrets/jwt/operator/local/account/myaccount/user/user
Key    Value
---    -----
jwt    eyJ0eXAiOiJKV1QiLCJhbGciOiJlZDI1NTE5LW5rZXkifQ.eyJqdGkiOiJIN0xHVFBQV0ZYWElJNlJDT0syR1FRSUFIMjc0QVJYWEZHREJTSjdKNEZTUlREMlQ0VFRBIiwiaWF0IjoxNzEyNzMxNDc5LCJpc3MiOiJBQ0szNE5CVlBXN05DNDRaRjdBUU1LVUxJSUxRNERGRDZDQkdBTjNMR1lHVkNFSkVYQVlZQzJYSyIsInN1YiI6IlVBQlBPUTNVM0pDU1dXRjVTT0VVT1JOUU43SlRaTkZLREVGRk9XUTdSTVE0UVBHSUpPNDRONVFYIiwibmF0cyI6eyJwdWIiOnt9LCJzdWIiOnt9LCJzdWJzIjotMSwiZGF0YSI6LTEsInBheWxvYWQiOi0xLCJ0eXBlIjoidXNlciIsInZlcnNpb24iOjJ9fQ.nY1tzhGXtj3THn8vu4L9TtyqE_fXApqTuGErigAu1QrDfklFftvwLNS3qBWXnStXmKQJpi3HCCNzPHF2e_MCAw
``

However, the account is not trusted yet, because the operator does not exist yet to sign the account. So lets finish the complete chain of trust by creating the operator the account is hooked up with. 

```
$ vault write nats-secrets/issue/operator/local @operator/operator.json
Success! Data written to: nats-secrets/issue/operator/local

$ vault read nats-secrets/issue/operator/local 
Key                    Value
---                    -----
claims                 map[operator:map[accountServerUrl:nats://localhost:4222 signingKeys:[opsk1]]]
createSystemAccount    false
operator               local
status                 map[operator:map[jwt:true nkey:true] systemAccount:map[jwt:false nkey:false] systemAccountUser:map[jwt:false nkey:false]]
syncAccountServer      true

$ vault read nats-secrets/jwt/operator/local   
Key    Value
---    -----
jwt    eyJ0eXAiOiJKV1QiLCJhbGciOiJlZDI1NTE5LW5rZXkifQ.eyJqdGkiOiJJSTNQTjRSSUlaNEQyTEQyWkNWRjJXTkdCTFY2VUI0RERINlVPVVJMNzVCUFVUU09MQjRRIiwiaWF0IjoxNzEyNzMxNTkzLCJpc3MiOiJPQjdSV0gySVNQRjIyQTI0NkE3U04zSlpLSzJWVzRVT0w1NEpBUFQ0MzNGN1pUREZMQUNLSVpWTyIsInN1YiI6Ik9CN1JXSDJJU1BGMjJBMjQ2QTdTTjNKWktLMlZXNFVPTDU0SkFQVDQzM0Y3WlRERkxBQ0tJWlZPIiwibmF0cyI6eyJzaWduaW5nX2tleXMiOlsiT0FSNjVGSU1RWVFJU0s0S1BJTFlWWks3TTNQUllFU1NTRjVVT0FEMkxSNkVWTEpBMkNISjRHUTQiXSwiYWNjb3VudF9zZXJ2ZXJfdXJsIjoibmF0czovL2xvY2FsaG9zdDo0MjIyIiwidHlwZSI6Im9wZXJhdG9yIiwidmVyc2lvbiI6Mn19.y6_hVIontI02gwkq14JTxu1cKScbpfI2Qq5oB9fpSUMLF5faWcTRL3zb4aDIsN-eA-d9OFVe4kB_LQO6R4aeAQ
```

Now, the also the `account` JWT is created and can be listed

```
$ vault read nats-secrets/jwt/operator/local/account/myaccount          
Key    Value
---    -----
jwt    eyJ0eXAiOiJKV1QiLCJhbGciOiJlZDI1NTE5LW5rZXkifQ.eyJqdGkiOiJUTFJDQzNGRzdRWlQ2Qkk1VE9TQ0FUVU1SNlBZNU5LWk5CNVZSWkZBU1hLSUFKUUpPSFRRIiwiaWF0IjoxNzEyNzMxNTkzLCJpc3MiOiJPQjdSV0gySVNQRjIyQTI0NkE3U04zSlpLSzJWVzRVT0w1NEpBUFQ0MzNGN1pUREZMQUNLSVpWTyIsInN1YiI6IkFDSzM0TkJWUFc3TkM0NFpGN0FRTUtVTElJTFE0REZENkNCR0FOM0xHWUdWQ0VKRVhBWVlDMlhLIiwibmF0cyI6eyJsaW1pdHMiOnsic3VicyI6LTEsImRhdGEiOi0xLCJwYXlsb2FkIjotMSwiaW1wb3J0cyI6LTEsImV4cG9ydHMiOi0xLCJ3aWxkY2FyZHMiOnRydWUsImNvbm4iOi0xLCJsZWFmIjotMX0sImRlZmF1bHRfcGVybWlzc2lvbnMiOnsicHViIjp7fSwic3ViIjp7fX0sInR5cGUiOiJhY2NvdW50IiwidmVyc2lvbiI6Mn19.I1xfAjuhcxw5Nri8Sq5hO1faXK9riPfRkiOatPbsUEURS5MO5uYzM3Bh6GKti1dCxPSyTg_bTb3quyKHkBsMAw
```

So to answer your your question: the operator and account won't be created automatically. We can't guess the right parameters. However, creating issues for entities that cannot be signed yet will create the corresponding NKey for identification. 

In order to login to a NATS server, you need to start the server by using the operators credentials and let this vault plugin push against the NATS account resolver. These settings can be configured in the operators issue.

**Comment by ruspaul013** [comment]
Thank you @siredmar for the explanation.
